version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - .env # configure postgres
    volumes:
      - devdata:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports: 
      - 5432:5432
volumes:
  devdata: # named volumes can be managed easier using docker-compose